### ISSUE TITLE
Parser: Unicode group names and named group references 

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/regexp-tree#144]
Currently parser doesn't consider group reference as a reference since doesn't normalize Unicode names to check:

```
/(?<\u{41}\u0042AB>\k<AB\u{41}\u0042>)/u
```

This should recognize `\k<AB\u{41}\u0042` as a group reference (`ABAB`).

**Comment by rbuckton** [comment]
It also fails to recognize unicode group names:

```
spec-compliant › indices-array-unicode-property-names

    SyntaxError: 

    /(?<π>a)/u
      ^
    Unexpected token: "?" at 1:2.

      10 | describeEachMode(() => {
      11 |     it("indices-array-unicode-property-names", () => {
    > 12 |         parse('/(?<π>a)/u');
         |         ^
      13 |         // expect(exec.call(/(?<π>a)/u, "bab")!.indices.groups!.π).toEqual([1, 2]);
      14 |         // expect(exec.call(/(?<\u{03C0}>a)/u, "bab")!.indices.groups!.π).toEqual([1, 2]);
      15 |         // expect(exec.call(/(?<\u{03C0}>a)/u, "bab")!.indices.groups!.π).toEqual([1, 2]);

      at Object.throwUnexpectedToken (node_modules/regexp-tree/dist/parser/generated/regexp-tree.js:626:11)
      at unexpectedToken (node_modules/regexp-tree/dist/parser/generated/regexp-tree.js:1342:13)
      at Object.parse (node_modules/regexp-tree/dist/parser/generated/regexp-tree.js:785:9)
      at Object.<anonymous>.regexpTreeParser.parse (node_modules/regexp-tree/dist/parser/index.js:22:10)
      at Object.parse (node_modules/regexp-tree/dist/regexp-tree.js:57:19)
      at Object.it (__tests__/test262/indices-array-unicode-property-names.ts:12:9)
```
