### ISSUE TITLE
Some capture group names are converted to [object Object]

### ISSUE THREAD

**Issue by shinnn** [DmitrySoshnikov/regexp-tree#183]
When a `RegExp` has a named capture group `laaalaaaaaaaaaa`, it throws the following error.

```js
const {optimize} = require('regexp-tree'); // v0.1.10

const result = optimize(/(?<laaalaaaaaaaaaa>.*)/);

result._string;
//=> '/(?<[object Object]>.*)/', though I expect it to be ’/(?<laaalaaaaaaaaaa>.*)/'

result.toRegExp();
/* throws:
/Users/Shinnosuke/test/node_modules/regexp-tree/dist/transform/index.js:58
        this._regexp = new RegExp(this.getSource(), this._ast.flags);
                       ^

SyntaxError: Invalid regular expression: /(?<[object Object]>.*)/: Invalid capture group name
    at new RegExp (<anonymous>)
    at TransformResult.toRegExp (/Users/Shinnosuke/test/node_modules/regexp-tree/dist/transform/index.js:58:24)
    at Object.<anonymous> (/Users/Shinnosuke/test/test.js:8:8) */
```

I’m not sure why, but when the group name is `laaalaaaaaaaaa`, the number of whose trailing `a` is less than `laaalaaaaaaaaaa` by 1, it doesn’t throw any errors.

```js
const {optimize} = require('regexp-tree'); // v0.1.10

const result = optimize(/(?<laaalaaaaaaaaa>.*)/);

result._string;
//=> '/(?<laaalaaaaaaaaa>.*)/'

result.toRegExp();
//=> /(?<laaalaaaaaaaaa>.*)/
```

**Comment by DmitrySoshnikov** [comment]
Thanks; was a parser issue. Fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/0ca284e359768a67c14b20b140b8337e1d4f373c and in `v0.1.11`.

**Comment by shinnn** [comment]
@DmitrySoshnikov `v0.1.11` works as expected. Thanks for you very quick response and fix.
