### ISSUE TITLE
Broken optimization `/^[\p{Mc}\p{Me}\p{Mn}]$/` -> `/^[Mcen\p{}]$/`

### ISSUE THREAD

**Issue by coderaiser** [DmitrySoshnikov/regexp-tree#239]
```
invalid Unicode escape \p
```

Or

```js
SyntaxError: Invalid regular expression: /^[Mcen\p{}]$/: Invalid property name in character class
```

**Comment by coderaiser** [comment]
Also when trying to optimize ` /^[\p{Mc}\p{Me}\p{Mn}]$/u`:

```js
TypeError: Cannot read properties of undefined (reading 'codePoint')
    at getSortValue (/Users/coderaiser/putout/node_modules/regexp-tree/dist/optimizer/transforms/char-class-classranges-merge-transform.js:103:26)
    at sortCharClass (/Users/coderaiser/putout/node_modules/regexp-tree/dist/optimizer/transforms/char-class-classranges-merge-transform.js:63:16)
    at Array.sort (<anonymous>)
    at Object.CharacterClass (/Users/coderaiser/putout/node_modules/regexp-tree/dist/optimizer/transforms/char-class-classranges-merge-transform.js:35:17)
    at pre (/Users/coderaiser/putout/node_modules/regexp-tree/dist/traverse/index.js:218:55)
    at visit (/Users/coderaiser/putout/node_modules/regexp-tree/dist/traverse/index.js:41:13)
    at visit (/Users/coderaiser/putout/node_modules/regexp-tree/dist/traverse/index.js:80:15)
    at visit (/Users/coderaiser/putout/node_modules/regexp-tree/dist/traverse/index.js:88:15)
    at astTraverse (/Users/coderaiser/putout/node_modules/regexp-tree/dist/traverse/index.js:99:3)
    at Object.traverse (/Users/coderaiser/putout/node_modules/regexp-tree/dist/traverse/index.js:172:5)
```

**Comment by DmitrySoshnikov** [comment]
@coderaiser – thanks for reporting. I'll appreciate a PR on fixing this issue. CC @Golmote
